version: '3.9'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

  backend-user:
    build: .
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/dominio
    ports:
      - 3001:3000
    networks:
      - app-network
  
  backend-task:
    build: .
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/dominio
    ports:
      - 3002:3000
    networks:
      - app-network

  nginx:
    image: nginx
    restart: always
    ports:
      - 3003:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge